{% set version = "5.4.0" %}

package:
  name: miceforest
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/miceforest/miceforest-{{ version }}.tar.gz
  sha256: 8be132391ea0e9e14ccc1bb8419db706ebd70ea28c880e6fd643f74476a08a65

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - scipy >=1.6.0
    - lightgbm >=3.3.1
    - numpy
    - blosc
    - dill
    - pandas
    - seaborn >=0.11.0
    - matplotlib-base >=3.3.0

test:
  # Testing is done with Travis CI, see build results here:
  # https://travis-ci.com/github/AnotherSamWilson/miceforest
  # Testing is also done locally (Windows 10)
  imports:
    - miceforest
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/AnotherSamWilson/miceforest
  license: MIT
  license_family: MIT
  # LICENSE file has been included in future distributions to pypi.
  # Remove on second push.
  license_file: LICENSE
  summary: 'Fast multiple imputation with random forests.'
  description: |
    Multiple Imputation iteratively 'fills in' missing values in a dataset
    by modeling each variable as a function of the other variables. The
    function used in this package is random forests, because they have
    advantages which work well with the multiple imputation algorithm.
    For detailed information, see https://github.com/AnotherSamWilson/miceforest
  doc_url: https://miceforest.readthedocs.io/en/latest/
  dev_url: https://github.com/AnotherSamWilson/miceforest

extra:
  recipe-maintainers:
    - AnotherSamWilson
